
J3D = .;j3dcore.jar;j3dutils.jar;vecmath.jar 

all: SolarSystem.java
	javac -cp .;j3dcore.jar;j3dutils.jar;vecmath.jar SolarSystem.java

run: 
	java -cp .;j3dcore.jar;j3dutils.jar;vecm math.jar SolarSystem