
NAME = Hola

all: $(NAME).java
	javac -cp .;j3dcore.jar;j3dutils.jar;vecmath.jar $(NAME).java
run: $(NAME).class
	java -cp .;j3dcore.jar;j3dutils.jar;vecmath.jar $(NAME)
clean: 
	rm *.class
